name: bazzite-hyprland
description: Bazzite puro con Hyprland para mi RTX 3060
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - hyprland
      - sddm
      - kitty
      - waybar
      - wofi
      - xdg-desktop-portal-hyprland
      - qt6-qtwayland
      - dolphin
      - fastfetch
      - swww
    remove:
      - gnome-shell
      - gdm
      - nautilus
      - gnome-terminal

  - type: systemd
    system:
      enabled:
        - sddm.service
