# Configuración básica para generar la ISO de Bazzite
[installer]
browser = false

[background]
image = "/usr/share/backgrounds/bazzite/bazzite-default.png"

[solvers]
# Esto asegura que use la imagen que acabas de compilar
image = "ghcr.io/sarkval/bazzite-hyperland:latest"
