name: Build disk images
on:
  workflow_dispatch:
    inputs:
      recipe:
        description: 'Nombre de la receta (ej: recipe.yml)'
        default: 'recipe.yml'
        required: true
      arch:
        description: 'Arquitectura (amd64)'
        default: 'amd64'
        required: true

jobs:
  build-disk:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ github.event.inputs.recipe }}
          # Usamos la variable de entorno para pasar los comandos que fallaban
        env:
          # Esto desactiva la firma y activa la creación de la ISO
          BLUE_BUILD_BUILD_DISK: "true"
          BLUE_BUILD_EXTRA_FLAGS: "--no-sign"

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazzite-hyprland-iso
          path: |
            ./output/*.iso
            ./output/*.sha256
          if-no-files-found: warn
