name: Build disk images
on:
  workflow_dispatch:
    inputs:
      recipe:
        description: 'Receta a usar (nombre del archivo en la carpeta recipes)'
        default: 'recipe.yml'
        required: true
      arch:
        description: 'Arquitectura (amd64 para tu PC)'
        default: 'amd64'
        required: true

jobs:
  build-disk:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO
        uses: blue-build/github-action@v1.6.1
        with:
          recipe: ${{ github.event.inputs.recipe }}
          cli_version: v0.9.4
          # Esto genera la ISO usando tu carpeta disk-config
          build_disk: true
          # IMPORTANTE: Aquí se define donde se guarda temporalmente
          output_dir: ./output

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazzite-hyprland-iso
          path: ./output/*.iso
          if-no-files-found: error
          retention-days: 1
