name: Build disk images
on:
  workflow_dispatch:
    inputs:
      recipe:
        description: 'Receta a usar (ejemplo: recipe.yml)'
        default: 'recipe.yml'
        required: true
      arch:
        description: 'Arquitectura (Usa amd64 para tu PC)'
        default: 'amd64'
        required: true

jobs:
  build-disk:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO
        uses: blue-build/github-action@v1.6.1
        with:
          recipe: ${{ github.event.inputs.recipe }}
          cli_version: v0.9.4
          build_disk: true
          output_dir: ./output
          # Esta línea salta el error de las llaves de firma (cosign)
          extra_flags: "--no-sign"

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazzite-hyprland-iso
          path: ./output/*.iso
          if-no-files-found: error
          retention-days: 1
